Added method to support detached but pending timeout pollers
racker/salus-telemetry-etcd-adapter pull request #71
Opened 2020-10-21 13:06 UTC by rohitsngh27

# Resolves
https://jira.rax.io/browse/SALUS-992

# What
Added method to support detached but pending timeout pollers

# How
Created a method in ZoneStorage to get pollers which are detached but pending timeout.

## How to test
This can be tested via unit test cases.

2020-10-21 13:06 UTC, rohitsngh27 commented
This is just an initial commit to check if I am following the right direction.

2020-10-21 13:27 UTC, jjbuchan reviewed
I think this looks good, but I imagine we'd want to get all per tenant as well as all per tenant per zone.

2020-10-21 16:23 UTC, itzg reviewed
Looking good and good refactoring.

@jjbuchan the per-tenant aspect will probably work out as is since the `ResolveZone` object conveys the zone name and optional tenant for private zones.

2020-10-21 16:25 UTC, rohitsngh27 commented
> I think this looks good, but I imagine we'd want to get all per tenant as well as all per tenant per zone.

2020-10-22 13:31 UTC, itzg submitted a review, later dismissed

2020-10-22 17:40 UTC, jjbuchan requested changes

2020-10-22 17:40 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
> +    public static final String FMT_ZONE_EXPIRING_IN_ZONE = "/zones/expiring/{tenant}/{zoneName}/";
I might still be missing something related to getting all per tenant, but I'd imagine we might not want a trailing `/` here?

If we want all for tenant `12345` would we query `/zones/expiring/12345/{null}` -> `/zones/expiring/12345/`

The trailing slash might cause nothing to be found in that case?

2020-10-22 17:40 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
> +    public static final String FMT_ZONE_EXPIRING_IN_ZONE = "/zones/expiring/{tenant}/{zoneName}/";
A test case for that could be good if I'm understanding things correctly.

2020-10-22 17:42 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
> +    public static final String FMT_ZONE_EXPIRING_IN_ZONE = "/zones/expiring/{tenant}/{zoneName}/";
So a new api to be added for this which gets all detached pending timeout pollars for a tenant?

2020-10-22 18:04 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
> +    public static final String FMT_ZONE_EXPIRING_IN_ZONE = "/zones/expiring/{tenant}/{zoneName}/";
My comment over here should help clarify - https://github.com/racker/salus-telemetry-zone-watcher/pull/24#discussion_r510354354

2020-10-22 18:42 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
> +    public static final String FMT_ZONE_EXPIRING_IN_ZONE = "/zones/expiring/{tenant}/{zoneName}/";
FYI, yes, the trailing slash in `/zones/expiring/12345/` would be important to differentiate from matching a tenant `123456` where a prefix of `/zones/expiring/12345` would match both tenants' keys.

2020-10-23 12:07 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
> +    public static final String FMT_ZONE_EXPIRING_IN_ZONE = "/zones/expiring/{tenant}/{zoneName}/";
Added new test case which checks for the per tenant all zones scenario

2020-10-23 16:58 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
> +    public static final String FMT_ZONE_EXPIRING_IN_ZONE = "/zones/expiring/{tenant}/{zoneName}";
I think you'll need a separate key since the trailing slash, when `zoneName` is specified, will be beneficial to avoid prefix mismatches. Or...you could adjust the code to append a slash when `zoneName` is passed as a blank string/null.

2020-10-23 17:03 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
> +    public static final String FMT_ZONE_EXPIRING_IN_ZONE = "/zones/expiring/{tenant}/{zoneName}";
If I use `/zones/expiring/{tenant}/{zoneName}/` it will work fine if zoneName is specifed but when zoneName is empty("") this will be `/zones/expiring/{tenant}//.` So I guess I have to remove the extra slash when the zoneName is empty("").

2020-10-23 17:05 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/etcd/types/Keys.java
> +    public static final String FMT_ZONE_EXPIRING_IN_ZONE = "/zones/expiring/{tenant}/{zoneName}";
Yeah or keep it as you have it `"/zones/expiring/{tenant}/{zoneName}"` and append a slash when `zoneName` is not blank.

2020-10-23 18:05 UTC, itzg approved these changes

2020-10-23 18:50 UTC, jjbuchan approved these changes

2020-10-28 14:34 UTC, itzg submitted a review, later dismissed
Optional change but still looking good overall

2020-10-28 14:34 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorage.java
> +  public CompletableFuture<List<String>> getExpiredPollerResourceIdsInZone(ResolvedZone zone) {
optional nit:
```suggestion
  public CompletableFuture<List<String>> getExpiringPollerResourceIdsInZone(ResolvedZone zone) {
```

2020-10-28 14:34 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
> +  public void testGetExpiredPollerResourceIdsInZone() throws InterruptedException {
if changing the other
```suggestion
  public void testGetExpiringPollerResourceIdsInZone() throws InterruptedException {
```

2020-10-28 17:20 UTC, jjbuchan requested changes
Looks good.  Just a minor change.

2020-10-29 16:14 UTC, jjbuchan approved these changes

2020-10-29 17:14 UTC, itzg approved these changes

2020-10-29 17:14 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
> -  public void testGetExpiredPollerResourceIds_PerTenant_AllZones() {
This test was removed since monitor-management iterates over them explicitly?

2020-10-29 17:15 UTC, rohitsngh27 commented on src/test/java/com/rackspace/salus/telemetry/etcd/services/ZoneStorageTest.java
> -  public void testGetExpiredPollerResourceIds_PerTenant_AllZones() {
Yes, This was added when we had the case of handling a tenant with no zone provided.

2020-10-29 17:49 UTC, merged